// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjrfxdnjjvmjgfftrndd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqcmZ4ZG5qanZtamdmZnRybmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDE4ODMsImV4cCI6MjA2MDg3Nzg4M30.KBljs1FxfRR-GSvlMPtVREZZg9vXMfh40fsvas8iseM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});